### PR TITLE
Fixed error handling to return CORS compliant error responses 

### PR DESCRIPTION
**Pull request by stephenhand**
when playback fails. 

Default port is now 61417 in line with other Servirtium impls. 

Standalone Server should shut down gracefully when sent a SIGTERM on Linux (like Docker does) as originally intended now.

### CODE REVIEW

**Comment by paul-hammant** [comment]
Hey Mr - watch some TV too !!!!!

**Comment by stephenhand** [comment]
No need for concern, I've just bought 'Oxygen Not Included' off Steam, so that's where my free time will be going for the next few days :-).

**Comment by paul-hammant** [comment]
Chortle!

**Comment by paul-hammant** [comment]
Hey Mr H, take a look at https://github.com/servirtium/compatibility-suite-runner (instructions within)

Also new files in the this repo - `docker-compose.yml` and `build.sh` (perhaps to be duplicated into build.bat too)

**Comment by paul-hammant** [comment]
Question: Can we also compile inside docker containers?  Not the main way of developing for someone wanting to make an enhancement or fix a bug for an impl, but n admirable way for noobs to do step 1 on the way to running the compatibility suite.

**Comment by stephenhand** [comment]
Certainly can, MS provides images for doing .NET Core builds in docker.

Probably best as a separate script to the compatibility test that builds the project then builds a local docker image (which I'd say is best as separate command run outside the build container? No docker in docker shenanigans needed then).

Run that and you should be gtg to run the compatibility script

**Comment by paul-hammant** [comment]
I've made a https://github.com/servirtium/servirtium-dotnet/blob/master/COMPATIBILITY_SUITE.md doc. At the bottom there's a TODO where we could furnish the docker incantations to do a build that way :)

**Comment by paul-hammant** [comment]
I moved a bash script to the new runner repo - https://github.com/servirtium/compatibility-suite-runner/blob/main/compare_recording_with_reference_case.sh

Migrating that to Python and including it in the existing python script seems logical

The shell script does a bunch of pasteurisation though - fixing up dates etc. Should it though, or is that the business of the standalone-server setup - a bunch of change/redact/remove settings on the recorder?   Thoughts?

**Pull request merged**
