### PR TITLE
Concurrency fixes

### PR DESCRIPTION
**Pull request by stephenhand**
Can now handle tests where several concurrent requests are made and their ordering isn't deterministic

### CODE REVIEW

**Comment by paul-hammant** [comment]
I think I deleted the python file, Mr ....

**Comment by paul-hammant** [comment]
Where are you encountering non-deterministic ordering of interactions?

**Comment by stephenhand** [comment]
> I think I deleted the python file, Mr ....

Yes, sorry, didn't see that before I merged. The dockery version has the original name now

**Comment by stephenhand** [comment]
`changes to a todo are persisted and show up when re-fetching the todo` makes 2 GET requests (to the root and for an item) very close together - they seem to leave the client in a deterministic order, but they can hit the Servirtium server in the opposite order - causing the test to fail if the playback order is different to the record order.

**Comment by stephenhand** [comment]
If other implementations aren't having the same issue I'd like to get to the bottom of that, but I think this is a good robustness enhancement in any event - systems under test making parallel, non interdependent requests that can occur in a non-deterministic order would be a common enough scenario I imagine.

**Comment by paul-hammant** [comment]
Well I spent a year thinking that the mocha suite could issue requests in parallel, then one by one the lang implementations could be fixed up to pass consistently for record and playback, disproving the parallel hypothesis.  All bar the original Java one - which should be deleted at this stage @daviddenton's Kotlin one is far better.  I thought you were encountering a parallel situation in the workplace, but no.

**Comment by stephenhand** [comment]
The mocha suite does issue requests in parallel - the fact that this fix works proves that. 

The fix works by waiting a short amount of time for more requests to come in before sending back a response if the first interaction it checks fails. 

If the mocha suite wasn't sending anything in parallel, this fix wouldn't make any difference

**Comment by stephenhand** [comment]
mocha-parallel

This is the network tab from the dev tools running the mocha suite - the waterfall shows a couple of requests running in parallel.

I think it's only those 2, but I'm pretty sure they are running concurrently

**Comment by paul-hammant** [comment]
Interesting - I'll spend more time with the other impls trying  to get a similar failure. I mean, I'll a loop to a script and watch TV like any normal lazy person.

**Comment by stephenhand** [comment]
> Interesting - I'll spend more time with the other impls trying to get a similar failure. I mean, I'll a loop to a script and watch TV like any normal lazy person.

Thanks - it looks like this 'fix' still has some issues, so could be wrong on this - still looking into it, but I'm pretty sure those requests in the mocha test go concurrently.

To be clear, I think the requests are SENT in a predictable order, but wait for the responses concurrently.

For some reason, what I'm seeing in the .NET version is that the HTTP requests are being received by the server in the opposite order to them being sent by the client - which I know is technically possible on the internet, but I'd have thought pretty rare - so it's weird it's happening so often in the .NET server, which is what I want to look into a bit more.

If the other implementations were always receiving the requests in the order they are being sent, they probably wouldn't see an issue (the .NET version wouldn't see an issue either).

**Comment by paul-hammant** [comment]
Async is a scaling feature for server-side technologies, for sure.

But in test-automation we are primarily interested in functional correctness, and it seems OK to me to force  serial operation. For example, when running Servirtium as a DLL in-process with NUnit, then the test runner is the only usage of that instance. Your colleague in the adjacent cube ^H^H^H^H^H town in their bedroom running the same test at the same time is in their own instance shared-nothing with you. The prior generation of SV tools would have a single server running between devs/QAs/bot and the QA instance of the stack. A super-suck situation.  It's a little bit of a stretch to say that Servirtium will always be used for truly sequential operations, but I think it is generally true. Now you mention it I think I had the same bug a year ago - the interaction counter had to incremented on new request and held, not after or on response-ready.

**Comment by stephenhand** [comment]
I agree it's totally reasonable to expect the test logic to be sequential. However I don't think it's reasonable to expect the logic under test to always be in sequential, it's pretty normal for services in multi service architectures (microservices, SOA or whatever other flavour) to make multiple secondary HTTP calls in parallel to service a request.

As a (contrived, I admit) example - you are writing a test for an endpoint on a checkout service. The test logic is just a single HTTP call.  However, to do it's work, the checkout service needs to query an inventory service for each item being checked out to ensure it's in stock. The inventory checks for each item aren't interdependent so the service kicks them all off in parallel to speed up the overall checkout operation. The order that these calls are made or that the responses are received in is unimportant.

If Servirtium doesn't have some support to allow concurrent requests, the above logic couldn't be tested, you would have to force the service to make the calls in sequence.

**Comment by paul-hammant** [comment]
I think Pete's mocha suite is an interesting talking point here. When I was previously chasing timing problems, I was chatting to Peter about where we could change it to be sequential. He responded that he though it was, so I was double checking my assumptions. But you're right we shouldn't change the SUT to be more testable when it is already perfectly decomposed.

Most usages of Sv are going to be one, two or three IOs, as good teams are going to be good at decomposition.  Regardless, out test suites for ourselves should be more exhaustive, and more contrived is fine towards that.

The checkout:inventory scenario .. if I were developing-testing a component that interacted with down-stack checkout & inventory services, I might configure two Servirtium middle thingies say inventory on 61417, and checkout on 61418 Both setup in before() and both torn down in after(). Each with a separate markdown recording perhaps.  At least, that's if there was a chance of order non-determinism for those two services. 

If there wasn't non-deterministic order I might have them in **one** servirtium listener.  Of course, if this is third-party services we're recording/playing back they would have hard-coded the endpoint for both, so we can't choose localhost:something instead let alone separate them. That mode of operation has to be http proxy server of the real thing instead of a middle-man that's not a http-proxy server. Servirtium is unlikely to be a panacea. Same was true for Selenium, when you were embroiled in DOM fu from outside the team.

**Comment by stephenhand** [comment]
I was thinking more trying to test the checkout component in that scenario, using Servirtium to record / playback it's interactions with the inventory service (presumably in addition to other stuff). - that seems like a relatively straightforward and common enough use case which ideally Sv should be able to handle.

> Most usages of Sv are going to be one, two or three IOs, as good teams are going to be good at decomposition. Regardless, out test suites for ourselves should be more exhaustive, and more contrived is fine towards that.

I'm not sure this is a safe assumption, good teams haven't necessarily inherited good code, and they have to be able to test what's there, not just what should be there.

Anyways, this is a much bigger discussion, probably needs a better forum than a PR thread!

To wrap up I think the fix in this PR ( along with the fix of this fix in https://github.com/servirtium/servirtium-dotnet/pull/6 ) provides a way for Sv to treat unrelated requests as unrelated instead of forcing restrictions on the SUT, without introducing any extra burden on the test implementer (except an additional config parameter, which has a sensible default) or compromising the integrity of the testing overall. I'm not sure whether it should be a requirement for all Sv implementations to have this capability, but I think it's definitely an improvement.

I'm going to look into why the ordering of requests gets flipped sometimes from client > server, but it could just be a result of how the host web server is implemented, there's nothing forcing a web server to handle incoming requests in the order they are received, so it might just be one of those things. I'm going to log the first line where it hits my code - if they are already flipped then (I can already tell they are flipped pretty close to then from previous logs) I'm going to assume there's not much I can do about it.

Oh and Happy New Year!

**Comment by paul-hammant** [comment]
I mostly work in legacy-rejuvenation missions these days. and while I have strong ideals for micro-applications - https://paulhammant.com/2017/02/01/ui-component-testing/ - and also micro services, I do agree that it's hard when the codebase preexists.

I think you fixed in some commits that looked at the lifecycle of the interaction number, right?  Good work.

I pushed a change to the python. This towards All other impls being able to use this script for their compatibility suite invocation:

```
cd each/impls/checkout/dir
# build binaries
# make local docker image
/path/to/python3 -c "$(curl -fsSL https://raw.githubusercontent.com/servirtium/servirtium-dotnet/master/compatibility-suite.py)"
# profit
```

Thoughts?

**Comment by stephenhand** [comment]
Looks good! The dockery script will move to the separate repo we discussed at some point but that's just a URL change.

The script will need to parameterise the docker image it uses so each impl can pass in their own, but again, straightforward enough

**Pull request merged**
